package com.gov.subsidy.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Startup component that cleans up legacy PostgreSQL enum check constraints
 * generated by Hibernate ddl-auto=update when new ApplicationStatus,
 * WorkflowStage, or WorkflowEvent values are added to Java enums.
 */
@Component
public class DatabaseConstraintInitializer implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DatabaseConstraintInitializer.class);
    private final JdbcTemplate jdbcTemplate;

    public DatabaseConstraintInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        String createTableSql = """
            CREATE TABLE IF NOT EXISTS application_documents (
                id BIGSERIAL PRIMARY KEY,
                application_id BIGINT NOT NULL,
                beneficiary_id BIGINT NOT NULL,
                scheme_id BIGINT NOT NULL,
                document_type VARCHAR(150) NOT NULL,
                original_file_name VARCHAR(255) NOT NULL,
                storage_path TEXT NOT NULL,
                file_size BIGINT,
                content_type VARCHAR(100),
                upload_timestamp TIMESTAMP NOT NULL
            )
            """;
        try {
            jdbcTemplate.execute(createTableSql);
            log.info("Ensured table application_documents exists in database");
        } catch (Exception e) {
            log.warn("Table creation warning: {}", e.getMessage());
        }

        String[] dropQueries = {
            "ALTER TABLE applications DROP CONSTRAINT IF EXISTS applications_workflow_status_check",
            "ALTER TABLE applications DROP CONSTRAINT IF EXISTS applications_current_stage_check",
            "ALTER TABLE applications DROP CONSTRAINT IF EXISTS applications_eligibility_result_check",
            "ALTER TABLE verifications DROP CONSTRAINT IF EXISTS verifications_status_check",
            "ALTER TABLE workflow_audit_logs DROP CONSTRAINT IF EXISTS workflow_audit_logs_event_check",
            "ALTER TABLE workflow_audit_logs DROP CONSTRAINT IF EXISTS workflow_audit_logs_from_status_check",
            "ALTER TABLE workflow_audit_logs DROP CONSTRAINT IF EXISTS workflow_audit_logs_to_status_check",
            "ALTER TABLE workflow_audit_logs DROP CONSTRAINT IF EXISTS workflow_audit_logs_from_stage_check",
            "ALTER TABLE workflow_audit_logs DROP CONSTRAINT IF EXISTS workflow_audit_logs_to_stage_check"
        };

        for (String sql : dropQueries) {
            try {
                jdbcTemplate.execute(sql);
                log.info("Database constraint cleanup executed: {}", sql);
            } catch (Exception e) {
                log.warn("Database constraint cleanup ignored ({}): {}", sql, e.getMessage());
            }
        }
    }
}
